import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {database} from '../scripts/sqlite-adapter.mjs';
import {api,passwordHash} from '../server/worker.mjs';
async function setup(){const DB=database();DB.raw.exec(readFileSync(new URL('../migrations/0001_initial.sql',import.meta.url),'utf8'));DB.raw.exec(readFileSync(new URL('../migrations/0002_confirmation_email.sql',import.meta.url),'utf8'));const env={DB,ADMIN_PASSWORD_HASH:await passwordHash('test-owner-password'),SESSION_SECRET:'testing-only-secret-never-deploy'};const call=(path,body,token)=>api(new Request('http://localhost/api'+path,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:body===undefined?undefined:JSON.stringify(body)}),env);await call('/catalog');const login=await call('/login',{password:'test-owner-password'});const {token}=await login.json();return {DB,call,token};}
const order=(items=[{id:'original',quantity:1}])=>({request_key:crypto.randomUUID(),name:'Test Baker',phone:'8065550123',email:'test@example.com',items,payment_note:''});
test('catalog matches source menu, prices, and starts closed',async()=>{const {call}=await setup();const c=await (await call('/catalog')).json();assert.equal(c.products.length,18);assert.equal(c.products.find(p=>p.id==='flight').price,2000);assert.equal(c.products.find(p=>p.id==='cookies-24').price,1700);assert.ok(c.categories.every(c=>!c.open));assert.ok(c.products.every(p=>p.stock===0));});
test('private customer data and stock mutations reject anonymous requests',async()=>{const {call}=await setup();assert.equal((await call('/admin/overview')).status,401);assert.equal((await call('/admin/category',{id:'cookies',open:1})).status,401);assert.equal((await call('/login',{password:'wrong'})).status,401);});
test('last loaf cannot be oversold and rejected order is rolled back',async()=>{const {call,DB}=await setup();DB.raw.exec("UPDATE categories SET open=1 WHERE id='sourdough'; UPDATE products SET stock=1 WHERE id='original'");const responses=await Promise.all([call('/orders',order()),call('/orders',order())]);assert.deepEqual(responses.map(r=>r.status).sort(),[201,409]);assert.equal(DB.raw.prepare("SELECT stock FROM products WHERE id='original'").get().stock,0);assert.equal(DB.raw.prepare('SELECT count(*) n FROM orders').get().n,1);});
test('mixed basket is all-or-nothing when cookies are paused',async()=>{const {call,DB}=await setup();DB.raw.exec("UPDATE categories SET open=1 WHERE id='sourdough'; UPDATE products SET stock=10");const r=await call('/orders',order([{id:'original',quantity:2},{id:'cookies-6',quantity:1}]));assert.equal(r.status,409);assert.equal(DB.raw.prepare("SELECT stock FROM products WHERE id='original'").get().stock,10);assert.equal(DB.raw.prepare('SELECT count(*) n FROM orders').get().n,0);});
test('idempotent retries do not double-reserve stock and totals ignore client prices',async()=>{const {call,DB}=await setup();DB.raw.exec('UPDATE categories SET open=1; UPDATE products SET stock=10');const b=order([{id:'original',quantity:2,price:1}]);const r1=await (await call('/orders',b)).json();const r2=await (await call('/orders',b)).json();assert.equal(r1.id,r2.id);assert.equal(r1.total,2000);assert.equal(DB.raw.prepare("SELECT stock FROM products WHERE id='original'").get().stock,8);assert.equal((await call('/orders',{...b,name:'Different person'})).status,409);});
test('cancellation restores stock exactly once and cannot reopen',async()=>{const {call,DB,token}=await setup();DB.raw.exec('UPDATE categories SET open=1; UPDATE products SET stock=10');const o=await (await call('/orders',order())).json();assert.equal((await call('/admin/order',{id:o.id,status:'cancelled'},token)).status,200);await call('/admin/order',{id:o.id,status:'cancelled'},token);assert.equal(DB.raw.prepare("SELECT stock FROM products WHERE id='original'").get().stock,10);assert.equal((await call('/admin/order',{id:o.id,status:'paid'},token)).status,409);});
test('flight requires four distinct flavors and preserves other response',async()=>{const {call,DB}=await setup();DB.raw.exec('UPDATE categories SET open=1; UPDATE products SET stock=10');assert.equal((await call('/orders',order([{id:'flight',quantity:1,flavors:['Original']}]))).status,400);assert.equal((await call('/orders',order([{id:'flight',quantity:1,flavors:['Original','Original','Pizza Loaf','Chocolate Chip']}]))).status,400);assert.equal((await call('/orders',order([{id:'flight',quantity:1,flavors:['Original','Chocolate Chip','Pizza Loaf','Other custom flavor']}]))).status,201);});
test('stock rejects negative quantities and session signatures cannot be forged',async()=>{const {call}=await setup();assert.equal((await call('/orders',order([{id:'original',quantity:-1}]))).status,400);assert.equal((await call('/admin/overview',undefined,`${Date.now()+60000}.fake.${'0'.repeat(64)}`)).status,401);});
test('giveaway draw uses eligible deduplicated pool and locks the result',async()=>{const {call,token}=await setup();const g=await (await call('/admin/giveaway',{title:'Test draw',media_id:'offline-test',require_like:1,require_share:1},token)).json();const entry={giveaway_id:g.id,username:'eligible_baker',commented:1,liked:1,shared:1,note:'Manually checked'};await call('/admin/entry',entry,token);await call('/admin/entry',{...entry,username:'@ELIGIBLE_BAKER'},token);await call('/admin/entry',{...entry,username:'ineligible',shared:0},token);const draw=await (await call('/admin/draw',{id:g.id},token)).json();assert.equal(draw.winner,'eligible_baker');assert.equal((await call('/admin/entry',entry,token)).status,409);const again=await (await call('/admin/draw',{id:g.id},token)).json();assert.equal(again.winner,draw.winner);});
test('cross-origin writes and login brute force are rejected',async()=>{const {call,DB}=await setup();const env={DB,SESSION_SECRET:'test'};assert.equal((await api(new Request('http://localhost/api/orders',{method:'POST',headers:{Origin:'https://untrusted.example','Content-Type':'application/json'},body:'{}'}),env)).status,403);let response;for(let i=0;i<9;i++)response=await call('/login',{password:'wrong'});assert.equal(response.status,429);});
test('stale manager edits cannot overwrite stock reserved by a customer',async()=>{const {call,DB,token}=await setup();DB.raw.exec('UPDATE categories SET open=1; UPDATE products SET stock=10');const c=await (await call('/catalog')).json();const p=c.products.find(p=>p.id==='original');await call('/orders',order());const response=await call('/admin/product',{...p,expected_stock:10,stock:20},token);assert.equal(response.status,409);assert.equal(DB.raw.prepare("SELECT stock FROM products WHERE id='original'").get().stock,9);assert.equal((await call('/admin/product',{...p,expected_stock:9,stock:20},token)).status,200);});
