import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {database} from '../scripts/sqlite-adapter.mjs';
import {api,placeOrder} from '../server/worker.mjs';
import {dispatchConfirmation,syncSubscribers,confirmationMessage} from '../server/email.mjs';
async function setup(){const DB=database();for(const file of ['0001_initial.sql','0002_confirmation_email.sql','0003_unlimited_inventory.sql'])DB.raw.exec(readFileSync(new URL('../migrations/'+file,import.meta.url),'utf8'));await api(new Request('http://localhost/api/catalog'),{DB});DB.raw.exec('UPDATE categories SET open=1; UPDATE products SET stock=20');return DB;}
const input=(extra={})=>({name:'Test Customer',phone:'8065550123',email:'test@example.com',request_key:crypto.randomUUID(),items:[{id:'original',quantity:2}],...extra});
test('order, receipt outbox and optional signup commit together, once',async()=>{const DB=await setup(),b=input({marketing_opt_in:true});const o=await placeOrder(DB,b);await placeOrder(DB,b);assert.equal(DB.raw.prepare('SELECT count(*) n FROM email_outbox').get().n,1);assert.equal(DB.raw.prepare('SELECT count(*) n FROM newsletter_signups').get().n,1);const content=JSON.parse(DB.raw.prepare('SELECT content FROM email_outbox WHERE order_id=?').get(o.id).content);assert.equal(content.total,2000);assert.equal(content.email,b.email);});
test('sold-out orders do not queue email or add announcement contacts',async()=>{const DB=await setup();DB.raw.exec("UPDATE products SET stock=0 WHERE id='original'");await assert.rejects(()=>placeOrder(DB,input({marketing_opt_in:true})));assert.equal(DB.raw.prepare('SELECT count(*) n FROM email_outbox').get().n,0);assert.equal(DB.raw.prepare('SELECT count(*) n FROM newsletter_signups').get().n,0);});
test('ordinary order does not subscribe customer and invalid email is rejected',async()=>{const DB=await setup();await placeOrder(DB,input());assert.equal(DB.raw.prepare('SELECT count(*) n FROM newsletter_signups').get().n,0);await assert.rejects(()=>placeOrder(DB,input({email:'bad-address'})));});
test('no email configuration leaves order queued without claiming sent',async()=>{const DB=await setup(),o=await placeOrder(DB,input());const result=await dispatchConfirmation({DB},o.id,()=>assert.fail('Must not send'));assert.equal(result.status,'not_configured');assert.equal(DB.raw.prepare('SELECT status FROM email_outbox').get().status,'queued');});
test('successful email records provider acceptance and is not resent',async()=>{const DB=await setup(),o=await placeOrder(DB,input());let calls=0;const env={DB,BREVO_API_KEY:'test-key',EMAIL_FROM:'bakery@example.com'};const send=async(url,options)=>{calls++;assert.equal(url,'https://api.brevo.com/v3/smtp/email');const b=JSON.parse(options.body);assert.equal(b.headers.idempotencyKey,o.id);assert.equal(b.to[0].email,'test@example.com');return Response.json({messageId:'provider-receipt'});};assert.equal((await dispatchConfirmation(env,o.id,send)).status,'accepted');await dispatchConfirmation(env,o.id,send);assert.equal(calls,1);});
test('uncertain retry keeps identical payload and stops before provider dedupe expiry',async()=>{const DB=await setup(),o=await placeOrder(DB,input());const env={DB,BREVO_API_KEY:'key',EMAIL_FROM:'bakery@example.com'},now=Date.now(),sent=[];const send=async(url,options)=>{sent.push(options.body);throw new Error('Network error');};await dispatchConfirmation(env,o.id,send,now);await dispatchConfirmation({...env,EMAIL_FROM:'changed@example.com'},o.id,send,now+120001);assert.equal(sent[0],sent[1]);assert.equal((await dispatchConfirmation(env,o.id,send,now+13*60000)).status,'failed');assert.equal(sent.length,2);assert.equal(DB.raw.prepare("SELECT stock FROM products WHERE id='original'").get().stock,18);});
test('subscriber sync includes only opted-in contacts and preserves provider suppression',async()=>{const DB=await setup();await placeOrder(DB,input({marketing_opt_in:true}));await placeOrder(DB,input({email:'not-subscribed@example.com'}));const payloads=[];await syncSubscribers({DB,BREVO_API_KEY:'key',EMAIL_FROM:'bakery@example.com',BREVO_LIST_ID:4},async(url,options)=>{payloads.push(JSON.parse(options.body));return new Response(null,{status:204});});assert.equal(payloads.length,1);assert.equal(payloads[0].email,'test@example.com');assert.equal('emailBlacklisted' in payloads[0],false);assert.deepEqual(payloads[0].listIds,[4]);});
test('confirmation escapes user text and does not claim payment was received',()=>{const m=confirmationMessage({id:'abcde12345',name:'<img src=x>',items:[],total:0,pickup:'<script>bad</script>',venmo:'bakery'});assert.ok(!m.html.includes('<script>'));assert.ok(m.html.includes('&lt;img'));assert.ok(m.text.includes('not payment'));});
