import {products,defaults,flavors} from './catalog.mjs';
import {dispatchConfirmation,flushConfirmations,syncSubscribers,brevo} from './email.mjs';
const enc = new TextEncoder();
const hex = b => [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('');
const unhex = s => Uint8Array.from(s.match(/../g)||[],h=>parseInt(h,16));
const json = (data,status=200) => new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
class HttpError extends Error {constructor(status,message){super(message);this.status=status;}}
const fail=(status,message)=>{throw new HttpError(status,message);};
const text=(value,max=200,required=true)=>{if(typeof value!=='string'||value.length>max||(required&&!value.trim()))fail(400,'Please check the required fields.');return value.trim();};
const integer=(n,min=0,max=100000)=>{if(!Number.isInteger(n)||n<min||n>max)fail(400,'Please enter a valid whole number.');return n;};
const stmt=(db,sql,...args)=>db.prepare(sql).bind(...args);
const rows=async(db,sql,...args)=>(await stmt(db,sql,...args).all()).results;
const one=(db,sql,...args)=>stmt(db,sql,...args).first();
export async function passwordHash(password,salt=hex(crypto.getRandomValues(new Uint8Array(16)))){const key=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']);return `${salt}:${hex(await crypto.subtle.deriveBits({name:'PBKDF2',salt:unhex(salt),iterations:100000,hash:'SHA-256'},key,256))}`;}
async function sign(value,secret){const key=await crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return hex(await crypto.subtle.sign('HMAC',key,enc.encode(value)));}
async function verify(value,signature,secret){if(!/^[a-f0-9]{64}$/.test(signature||''))return false;const key=await crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['verify']);return crypto.subtle.verify('HMAC',key,unhex(signature),enc.encode(value));}
async function protect(req,env){if(!env.SESSION_SECRET)fail(503,'The bakery office is not configured yet.');const token=(req.headers.get('Authorization')||'').replace(/^Bearer /,'');const [expiry,nonce,sig]=token.split('.');if(!expiry||!nonce||Number(expiry)<Date.now()||!await verify(`${expiry}.${nonce}`,sig,env.SESSION_SECRET))fail(401,'Please sign in to the bakery office.');}
async function crypt(value,secret,decrypt=false){const material=await crypto.subtle.digest('SHA-256',enc.encode(secret));const key=await crypto.subtle.importKey('raw',material,'AES-GCM',false,['encrypt','decrypt']);if(decrypt){const [iv,data]=value.split(':');return new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:unhex(iv)},key,unhex(data)));}const iv=crypto.getRandomValues(new Uint8Array(12));return `${hex(iv)}:${hex(await crypto.subtle.encrypt({name:'AES-GCM',iv},key,enc.encode(value)))}`;}
async function limit(db,req,scope,max){const ip=req.headers.get('cf-connecting-ip')||'local';const bucket=Math.floor(Date.now()/600000);const key=`${scope}:${ip}:${bucket}`;const row=await stmt(db,'INSERT INTO rate_limits(key,count,expires) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET count=count+1 RETURNING count',key,Date.now()+600000).first();if(row.count>max)fail(429,'Too many attempts. Please try again in 10 minutes.');await stmt(db,'DELETE FROM rate_limits WHERE expires < ?',Date.now()).run();}
async function seed(db){if(await one(db,"SELECT value FROM settings WHERE key='initialized'"))return;await db.batch([
 ...[['sourdough','Sourdough'],['cookies','Cookies'],['rolls','Cinnamon rolls']].map(([id,name])=>stmt(db,'INSERT OR IGNORE INTO categories(id,name) VALUES(?,?)',id,name)),
 ...products.map(p=>stmt(db,'INSERT OR IGNORE INTO products(id,name,category,price,featured,sort) VALUES(?,?,?,?,?,?)',p.id,p.name,p.category,p.price,p.featured,p.sort)),
 ...Object.entries(defaults).map(([k,v])=>stmt(db,'INSERT OR IGNORE INTO settings(key,value) VALUES(?,?)',k,v)),stmt(db,"INSERT OR IGNORE INTO settings(key,value) VALUES('initialized','1')")]);}
export async function catalog(db){const [p,c,s]=await Promise.all([rows(db,'SELECT * FROM products ORDER BY sort,id'),rows(db,'SELECT * FROM categories ORDER BY rowid'),rows(db,"SELECT * FROM settings WHERE key!='initialized'")]);return {products:p,categories:c,settings:Object.fromEntries(s.map(x=>[x.key,x.value])),flavors};}
async function readBody(req){const raw=await req.text();if(raw.length>40000)fail(413,'This request is too large.');try{return JSON.parse(raw);}catch{fail(400,'Invalid request.');}}
export async function placeOrder(db,b){
 const name=text(b.name,120),phone=text(b.phone,40),phoneKey=phone.replace(/\D/g,'');if(phoneKey.length<10||phoneKey.length>15)fail(400,'Please enter a valid pickup phone number.');
 const email=text(b.email,254).toLowerCase();if(!/^[^\s@<>]+@[^\s@<>]+\.[^\s@<>]+$/.test(email))fail(400,'Please enter a valid email address.');const optIn=b.marketing_opt_in===true;
 const requestKey=text(b.request_key,80);if(!/^[a-zA-Z0-9-]{16,80}$/.test(requestKey))fail(400,'Invalid order reference.');const paymentNote=text(b.payment_note??'',500,false);
 if(!Array.isArray(b.items)||!b.items.length||b.items.length>40)fail(400,'Please choose at least one bake.');
 const seen=new Set();const items=b.items.map(i=>{const id=text(i.id,80);if(seen.has(id))fail(400,'Duplicate item.');seen.add(id);const quantity=integer(i.quantity,1,50);let selected=[];if(id==='flight'){if(!Array.isArray(i.flavors)||i.flavors.length!==4)fail(400,'Choose exactly four different flight flavors.');selected=i.flavors.map(x=>text(x,80));if(new Set(selected.map(x=>x.toLowerCase())).size!==4)fail(400,'Choose four different flight flavors.');}return {id,quantity,flavors:selected};}).sort((a,b)=>a.id.localeCompare(b.id));
 const hash=hex(await crypto.subtle.digest('SHA-256',enc.encode(JSON.stringify({name,phone,email,optIn,items,paymentNote}))));
 const existing=await one(db,'SELECT id,total,request_hash FROM orders WHERE request_key=?',requestKey);if(existing){if(existing.request_hash!==hash)fail(409,'This order reference has already been used. Refresh before making a different order.');return {id:existing.id,total:existing.total};}
 const id=crypto.randomUUID();const commands=[stmt(db,'INSERT INTO orders(id,request_key,request_hash,name,phone,phone_key,payment_note,email,marketing_opt_in) VALUES(?,?,?,?,?,?,?,?,?)',id,requestKey,hash,name,phone,phoneKey,paymentNote,email,+optIn)];
 const receiptItems=[];
 for(const i of items){const p=await one(db,'SELECT * FROM products WHERE id=?',i.id);if(!p)fail(400,'An item is no longer available.');commands.push(stmt(db,'INSERT INTO order_items(order_id,product_id,name,quantity,unit_price,flavors) VALUES(?,?,?,?,?,?)',id,p.id,p.name,i.quantity,p.price,JSON.stringify(i.flavors)));receiptItems.push({...i,name:p.name,price:p.price});}
 const settings=Object.fromEntries((await rows(db,"SELECT key,value FROM settings WHERE key IN ('pickup','venmo')")).map(s=>[s.key,s.value]));
 commands.push(stmt(db,'INSERT INTO email_outbox(order_id,content) VALUES(?,?)',id,JSON.stringify({id,name,email,items:receiptItems,total:receiptItems.reduce((sum,i)=>sum+i.price*i.quantity,0),pickup:settings.pickup,venmo:settings.venmo})));
 if(optIn)commands.push(stmt(db,"INSERT OR IGNORE INTO newsletter_signups(email,consent_text) VALUES(?,?)",email,'Email me about new flavors and bakery updates. I can unsubscribe anytime.'));
 try{await db.batch(commands);}catch(e){const retry=await one(db,'SELECT id,total,request_hash FROM orders WHERE request_key=?',requestKey);if(retry?.request_hash===hash)return {id:retry.id,total:retry.total};if(String(e).includes('STOCK_CHANGED'))fail(409,'A bake sold out, ordering paused, or the menu changed. Please review your basket.');throw e;}
 return one(db,'SELECT id,total FROM orders WHERE id=?',id);
}
async function emailEnv(env){const connection=await one(env.DB,"SELECT * FROM integrations WHERE id='brevo'");if(!connection)return env;return {...env,BREVO_API_KEY:await crypt(connection.token,env.SESSION_SECRET,true),EMAIL_FROM:connection.username,BREVO_LIST_ID:Number(connection.account_id)};}
async function processEmail(env){const config=await emailEnv(env);await flushConfirmations(config);await syncSubscribers(config);}
async function graph(env,token,path,params={}){const version=env.INSTAGRAM_API_VERSION||'v25.0';if(!/^v\d+\.0$/.test(version))fail(503,'Instagram API version is not configured.');const url=new URL(`https://graph.instagram.com/${version}/${path}`);for(const[k,v]of Object.entries(params))url.searchParams.set(k,v);const r=await fetch(url,{headers:{Authorization:`Bearer ${token}`},signal:AbortSignal.timeout(20000)});const data=await r.json();if(!r.ok)fail(502,'Instagram could not complete the request. Check the connection, permissions, and token expiry.');return data;}
async function integration(db,env){const i=await one(db,"SELECT * FROM integrations WHERE id='instagram'");if(!i)fail(409,'Connect an Instagram professional account first.');return {...i,token:await crypt(i.token,env.SESSION_SECRET,true)};}
export async function api(req,env){const db=env.DB;if(!db)return json({error:'The bakery database is not connected yet.'},503);const url=new URL(req.url),path=url.pathname,method=req.method;
 try{
  if(method!=='GET'&&req.headers.get('Origin')&&req.headers.get('Origin')!==url.origin)fail(403,'This request must come from the bakery website.');
  if(method!=='GET'&&!(req.headers.get('Content-Type')||'').includes('application/json'))fail(415,'JSON is required.');
  await seed(db);
  if(path==='/api/catalog'&&method==='GET'){const c=await catalog(db);return json({...c,products:c.products.filter(p=>p.active).map(({stock,unlimited,...p})=>({...p,available:Boolean(unlimited||stock>0)}))});}
  if(path==='/api/login'&&method==='POST'){await limit(db,req,'login',8);if(!env.ADMIN_PASSWORD_HASH||!env.SESSION_SECRET)fail(503,'The bakery office is not configured yet.');const b=await readBody(req);const password=text(b.password,200);const candidate=await passwordHash(password,env.ADMIN_PASSWORD_HASH.split(':')[0]);const a=await sign(candidate,env.SESSION_SECRET),z=await sign(env.ADMIN_PASSWORD_HASH,env.SESSION_SECRET);if(a!==z)fail(401,'That password was not recognized.');const value=`${Date.now()+8*3600000}.${crypto.randomUUID()}`;return json({token:`${value}.${await sign(value,env.SESSION_SECRET)}`});}
  if(path==='/api/orders'&&method==='POST'){await limit(db,req,'orders',20);const order=await placeOrder(db,await readBody(req));let emailStatus='queued';try{emailStatus=(await dispatchConfirmation(await emailEnv(env),order.id)).status;}catch{}return json({...order,email_status:emailStatus},201);}
  if(!path.startsWith('/api/admin/'))fail(404,'Not found.');await protect(req,env);
  const b=method==='GET'?{}:await readBody(req);
  if(path==='/api/admin/email'&&method==='GET')return json({connection:await one(db,"SELECT username AS sender,account_id AS list_id FROM integrations WHERE id='brevo'"),queue:await rows(db,'SELECT order_id,status,last_error,accepted_at FROM email_outbox ORDER BY rowid DESC LIMIT 100'),signups:await rows(db,'SELECT email,opted_at,synced,last_error FROM newsletter_signups ORDER BY opted_at DESC')});
  if(path==='/api/admin/email-connect'&&method==='POST'){
   const key=text(b.key,4000),sender=text(b.sender,254).toLowerCase(),listId=integer(b.list_id,1,2147483647);
   const senders=await brevo(key,'/senders');if(!senders.senders?.some(s=>s.email.toLowerCase()===sender&&s.active))fail(400,'Verify this sender address in Brevo first.');
   await brevo(key,`/contacts/lists/${listId}`);
   await stmt(db,"INSERT INTO integrations(id,account_id,username,token) VALUES('brevo',?,?,?) ON CONFLICT(id) DO UPDATE SET account_id=excluded.account_id,username=excluded.username,token=excluded.token",String(listId),sender,await crypt(key,env.SESSION_SECRET)).run();return json({ok:true});
  }
  if(path==='/api/admin/email-process'&&method==='POST'){await processEmail(env);return json({ok:true});}
  if(path==='/api/admin/email-disconnect'&&method==='POST'){await stmt(db,"DELETE FROM integrations WHERE id='brevo'").run();return json({ok:true});}
  if(path==='/api/admin/overview'&&method==='GET'){const orders=await rows(db,'SELECT * FROM orders ORDER BY created_at DESC LIMIT 2000');const items=await rows(db,'SELECT * FROM order_items WHERE order_id IN (SELECT id FROM orders ORDER BY created_at DESC LIMIT 2000)');return json({orders:orders.map(o=>({...o,items:items.filter(i=>i.order_id===o.id)})),catalog:await catalog(db),notes:await rows(db,'SELECT * FROM customer_notes'),instagram:await one(db,"SELECT account_id,username FROM integrations WHERE id='instagram'")});}
  if(path==='/api/admin/category'&&method==='POST'){await stmt(db,'UPDATE categories SET open=? WHERE id=?',integer(b.open,0,1),text(b.id,30)).run();return json({ok:true});}
  if(path==='/api/admin/product'&&method==='POST'){const id=text(b.id,80),name=text(b.name,120),category=text(b.category,30);if(!['sourdough','cookies','rolls'].includes(category))fail(400,'Unknown category.');const expected=b.expected_stock===undefined?-1:integer(b.expected_stock,0,10000);const changed=await stmt(db,'INSERT INTO products(id,name,category,price,stock,active,featured,unlimited,sort) VALUES(?,?,?,?,?,?,?,?,100) ON CONFLICT(id) DO UPDATE SET name=excluded.name,category=excluded.category,price=excluded.price,stock=excluded.stock,active=excluded.active,featured=excluded.featured,unlimited=excluded.unlimited WHERE products.stock=? AND products.unlimited=? RETURNING id',id,name,category,integer(b.price,0,100000),integer(b.stock,0,10000),integer(b.active,0,1),integer(b.featured??0,0,1),integer(b.unlimited??0,0,1),expected,integer(b.expected_unlimited??0,0,1)).first();if(!changed)fail(409,'Stock changed while you were editing. Refresh the office before saving quantities.');return json({ok:true});}
  if(path==='/api/admin/settings'&&method==='POST'){const commands=[];for(const key of Object.keys(defaults)){if(!(key in b))continue;const value=text(b[key],1000,false);if(key==='ga_id'&&value&&!/^G-[A-Z0-9]{4,20}$/.test(value))fail(400,'Use a Google Analytics measurement ID starting with G-.');if(key==='venmo'&&!/^[a-zA-Z0-9_-]{1,60}$/.test(value))fail(400,'Use a Venmo username without @.');commands.push(stmt(db,'UPDATE settings SET value=? WHERE key=?',value,key));}if(commands.length)await db.batch(commands);return json({ok:true});}
  if(path==='/api/admin/order'&&method==='POST'){const id=text(b.id,80),status=text(b.status,30);if(!['new','paid','ready','collected','cancelled'].includes(status))fail(400,'Unknown order status.');const o=await one(db,'SELECT status FROM orders WHERE id=?',id);if(!o)fail(404,'Order not found.');if(o.status==='cancelled'&&status!=='cancelled')fail(409,'Cancelled orders cannot be reopened. Create a new order to reserve stock.');await stmt(db,"UPDATE orders SET status=? WHERE id=? AND status!='cancelled'",status,id).run();return json({ok:true});}
  if(path==='/api/admin/note'&&method==='POST'){await stmt(db,'INSERT INTO customer_notes(phone_key,note) VALUES(?,?) ON CONFLICT(phone_key) DO UPDATE SET note=excluded.note',text(b.phone_key,20),text(b.note,3000,false)).run();return json({ok:true});}
  if(path==='/api/admin/instagram'&&method==='POST'){if(b.disconnect){await stmt(db,"DELETE FROM integrations WHERE id='instagram'").run();return json({ok:true});}const token=text(b.token,4000);const profile=await graph(env,token,'me',{fields:'user_id,username'});if(!profile.user_id||!profile.username)fail(502,'Instagram did not return an account.');await stmt(db,"INSERT INTO integrations(id,account_id,username,token) VALUES('instagram',?,?,?) ON CONFLICT(id) DO UPDATE SET account_id=excluded.account_id,username=excluded.username,token=excluded.token",String(profile.user_id),profile.username,await crypt(token,env.SESSION_SECRET)).run();return json({username:profile.username});}
  if(path==='/api/admin/media'&&method==='GET'){const i=await integration(db,env);return json(await graph(env,i.token,`${i.account_id}/media`,{fields:'id,caption,permalink,like_count,comments_count',limit:'50'}));}
  if(path==='/api/admin/giveaways'&&method==='GET')return json({giveaways:await rows(db,'SELECT * FROM giveaways ORDER BY created_at DESC'),entries:await rows(db,'SELECT * FROM entries ORDER BY username')});
  if(path==='/api/admin/giveaway'&&method==='POST'){const id=crypto.randomUUID();await stmt(db,'INSERT INTO giveaways(id,title,media_id,require_like,require_share) VALUES(?,?,?,?,?)',id,text(b.title,150),text(b.media_id,60),integer(b.require_like,0,1),integer(b.require_share,0,1)).run();return json({id});}
  if(path==='/api/admin/entry'&&method==='POST'){const id=text(b.giveaway_id,80),g=await one(db,'SELECT * FROM giveaways WHERE id=?',id);if(!g)fail(404,'Giveaway not found.');if(g.winner)fail(409,'This giveaway is already drawn.');const username=text(b.username,30).replace(/^@/,'').toLowerCase();if(!/^[a-z0-9_.]{1,30}$/.test(username))fail(400,'Enter a valid Instagram username.');await stmt(db,"INSERT INTO entries(giveaway_id,username,commented,liked,shared,note) SELECT ?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM giveaways WHERE id=? AND winner IS NULL) ON CONFLICT(giveaway_id,username) DO UPDATE SET commented=excluded.commented,liked=excluded.liked,shared=excluded.shared,note=excluded.note",id,username,integer(b.commented,0,1),integer(b.liked,0,1),integer(b.shared,0,1),text(b.note??'',1000,false),id).run();return json({ok:true});}
  if(path==='/api/admin/sync'&&method==='POST'){const g=await one(db,'SELECT * FROM giveaways WHERE id=?',text(b.id,80));if(!g)fail(404,'Giveaway not found.');if(g.winner)fail(409,'This giveaway is already drawn.');if(!/^\d+$/.test(g.media_id))fail(400,'Use the numeric media ID from your connected Instagram posts.');const i=await integration(db,env);const owner=await graph(env,i.token,g.media_id,{fields:'username'});if(owner.username?.toLowerCase()!==i.username.toLowerCase())fail(403,'Choose a post owned by the connected account.');const after=text(b.after??'',1000,false);const data=await graph(env,i.token,`${g.media_id}/comments`,{fields:'id,text,username,timestamp',limit:'100',...(after?{after}:{})});const names=[...new Set((data.data||[]).map(c=>c.username?.toLowerCase()).filter(u=>u&&u!==i.username.toLowerCase()&&/^[a-z0-9_.]{1,30}$/.test(u)))];if(names.length)await db.batch(names.map(u=>stmt(db,"INSERT INTO entries(giveaway_id,username,commented) SELECT ?,?,1 WHERE EXISTS(SELECT 1 FROM giveaways WHERE id=? AND winner IS NULL) ON CONFLICT(giveaway_id,username) DO UPDATE SET commented=1",g.id,u,g.id)));return json({imported:names.length,after:data.paging?.next?data.paging?.cursors?.after:null});}
  if(path==='/api/admin/draw'&&method==='POST'){const id=text(b.id,80),g=await one(db,'SELECT * FROM giveaways WHERE id=?',id);if(!g)fail(404,'Giveaway not found.');if(g.winner)return json({winner:g.winner});const entries=await rows(db,'SELECT username FROM entries WHERE giveaway_id=? AND commented=1 AND (liked=1 OR ?=0) AND (shared=1 OR ?=0) ORDER BY username',id,g.require_like,g.require_share);if(!entries.length)fail(400,'No eligible entries yet.');const n=entries.length;let r;do{r=crypto.getRandomValues(new Uint32Array(1))[0];}while(r>=Math.floor(4294967296/n)*n);const winner=entries[r%n].username;await stmt(db,'UPDATE giveaways SET winner=?,drawn_at=CURRENT_TIMESTAMP,draw_pool=? WHERE id=? AND winner IS NULL',winner,JSON.stringify(entries.map(e=>e.username)),id).run();return json(await one(db,'SELECT winner,drawn_at FROM giveaways WHERE id=?',id));}
  fail(404,'Not found.');
 }catch(e){if(e instanceof HttpError)return json({error:e.message},e.status);console.error('Bakery API failed:',path,e.name);return json({error:'Something went wrong. Please try again. Your input has been kept.'},500);}
}
export default {async scheduled(event,env,ctx){ctx.waitUntil(processEmail(env));},async fetch(req,env){if(new URL(req.url).pathname.startsWith('/api/'))return api(req,env);const r=await env.ASSETS.fetch(req);const out=new Response(r.body,r);out.headers.set('X-Content-Type-Options','nosniff');out.headers.set('Referrer-Policy','strict-origin-when-cross-origin');out.headers.set('Content-Security-Policy',"default-src 'self'; script-src 'self' https://www.googletagmanager.com; style-src 'self' https://fonts.googleapis.com; font-src https://fonts.gstatic.com; img-src 'self' data: https://www.google-analytics.com; connect-src 'self' https://*.google-analytics.com https://www.googletagmanager.com; object-src 'none'; base-uri 'self'; frame-ancestors 'none'; form-action 'self'");return out;}};
